spring:
  data:
    mongodb:
      host: 54.218.25.49
      password: "*VyytvU^BXi2#sE,b0+6osCa,hqi}Oe]KAn#eH?hE2bSfTn,L%oW7YuHJmDnOabb"
      port: 27017
      username: siyi
      authentication-database: admin